name: Build and Deploy

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: build-artifact
    steps:
      - uses: actions/checkout@v4

      - name: Get claat
        run: |
          wget https://github.com/googlecodelabs/tools/releases/download/v2.0.2/claat-linux-amd64
          chmod +x claat-linux-amd64 
          
      - name: Run claat
        run: |
          cd TP_instructions
          ../claat-linux-amd64 export tp*.md
          sed -i 's/codelab-elements\//codelab-elements-tmp\//' tp*/index.html # Tmp fix linked to an issue with codelab elements see https://github.com/googlecodelabs/tools/issues/796

      - name: Create public directory
        run: mkdir _site

      - name: Copy files to public directory
        run: | 
          cp -r TP_instructions/* _site
          ls _site

      - uses: actions/upload-pages-artifact@v3
        id: upload
        with:
          path: _site

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
